import os
import sys
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from google.adk.agents import LlmAgent, SequentialAgent
from google.adk.tools.mcp_tool import MCPToolset
from google.adk.tools import FunctionTool
from mcp.client.stdio import StdioServerParameters

os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "true"
os.environ["GOOGLE_CLOUD_PROJECT"] = "nutri-plan-26"
os.environ["GOOGLE_CLOUD_LOCATION"] = "us-central1"

MODEL = "gemini-2.5-flash"

# --- MCP Toolsets ---

nutrition_tools = MCPToolset(
    connection_params=StdioServerParameters(
        command=sys.executable,
        args=["/app/nutrition_mcp_server.py"]
    )
)

maps_tools = MCPToolset(
    connection_params=StdioServerParameters(
        command="google-maps-mcp-server",
        env={"GOOGLE_MAPS_API_KEY": os.environ.get("GOOGLE_MAPS_API_KEY", "")}
    )
)

# --- Email Function Tool ---

async def send_plan_email(recipient_email: str, plan_content: str) -> dict:
    """
    Send the weekly meal plan and grocery list to the user's email.
    Args:
        recipient_email: Email address to send the plan to
        plan_content: The full plan content including meal plan, nutrition,
                      grocery list and stores
    """
    try:
        gmail_user = os.environ.get("GMAIL_USER", "")
        gmail_app_password = os.environ.get("GMAIL_APP_PASSWORD", "")

        if not gmail_user or not gmail_app_password:
            return {"success": False, "error": "Email credentials not configured"}

        msg = MIMEMultipart("alternative")
        msg["Subject"] = "🥗 Your NutriPlan Weekly Meal Plan & Grocery List"
        msg["From"] = gmail_user
        msg["To"] = recipient_email

        text_body = f"Your NutriPlan Weekly Meal Plan\n{'='*40}\n\n{plan_content}\n\n---\nGenerated by NutriPlan 🥗"

        html_body = f"""<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;max-width:640px;margin:0 auto;padding:20px;color:#333;">
  <h1 style="color:#2e7d32;padding-bottom:8px;border-bottom:2px solid #2e7d32;">
    🥗 NutriPlan &mdash; Your Weekly Plan
  </h1>
  <div style="background:#f9f9f9;padding:20px;border-radius:8px;border:1px solid #e0e0e0;
              white-space:pre-wrap;word-break:break-word;font-family:monospace;
              font-size:13px;line-height:1.7;">
{plan_content}
  </div>
  <p style="color:#aaa;font-size:11px;margin-top:16px;text-align:center;">
    Generated by NutriPlan 🥗
  </p>
</body>
</html>"""

        msg.attach(MIMEText(text_body, "plain"))
        msg.attach(MIMEText(html_body, "html"))

        server = smtplib.SMTP("smtp.gmail.com", 587)
        server.ehlo()
        server.starttls()
        server.login(gmail_user, gmail_app_password)
        server.sendmail(gmail_user, recipient_email, msg.as_string())
        server.quit()

        return {"success": True, "message": f"Email sent to {recipient_email}"}

    except Exception as e:
        return {"success": False, "error": str(e)}

email_tool = FunctionTool(send_plan_email)

# --- Sub Agents ---

profile_agent = LlmAgent(
    name="profile_agent",
    model=MODEL,
    output_key="user_profile",
    instruction="""Extract from the user's message:
    - dietary_restrictions: list (e.g. vegetarian, no seafood, no eggs)
    - weekly_budget_inr: number (default 2000)
    - num_people: number (default 2)
    - location: neighbourhood and city (default Bangalore)
    - calorie_target: daily calories per person if mentioned (default null)
    - macro_targets: object with protein_g, carbs_g, fat_g if mentioned (default null)
    Output ONLY a valid JSON object. No other text whatsoever."""
)

meal_planner_agent = LlmAgent(
    name="meal_planner_agent",
    model=MODEL,
    output_key="meal_plan",
    instruction="""You are an expert Indian meal planner and nutritionist.
    User profile is in session state as 'user_profile'.
    Create a 7-day Indian meal plan (breakfast, lunch, dinner).
    Rules:
    - Strictly respect ALL dietary restrictions
    - Hit calorie_target per person per day if set
    - Balance macros if macro_targets set
    - Simple, commonly available Indian ingredients
    - Stay within weekly budget
    - Good variety across the week

    Format EXACTLY like this for each day — no boxes, no lines, just clean text:

    Day 1 — Monday

      🌅 Breakfast — Masala Omelette + 2 Whole Wheat Rotis
         Calories: ~380 kcal  |  Protein: 18g  |  Carbs: 42g  |  Fat: 14g

      ☀️ Lunch — Rajma Chawal + Cucumber Raita
         Calories: ~520 kcal  |  Protein: 22g  |  Carbs: 78g  |  Fat: 8g

      🌙 Dinner — Palak Paneer + 2 Rotis + Salad
         Calories: ~490 kcal  |  Protein: 20g  |  Carbs: 48g  |  Fat: 18g

      Day Total — ~1390 kcal  |  Protein: 60g  |  Carbs: 168g  |  Fat: 40g


    Repeat this exact format for all 7 days with a blank line between days.

    After Day 7 add:

    WEEKLY NUTRITION SUMMARY

      Average per person per day:
      Calories  ~XXXX kcal
      Protein   ~XXg
      Carbs     ~XXXg
      Fat       ~XXg
      Fiber     ~XXg

      [One line: whether calorie and macro targets are met]

    Output only the meal plan. No intro sentence, no commentary."""
)

recipe_nutrition_agent = LlmAgent(
    name="recipe_nutrition_agent",
    model=MODEL,
    output_key="enriched_plan",
    tools=[nutrition_tools],
    instruction="""You are a nutrition analyst.
    Meal plan is in session state as 'meal_plan'.
    Use get_nutrition for 3-4 key ingredients to verify estimates.
    If MCP returns no data use your own knowledge.
    Output ONLY: "ok" — nothing else. The meal plan already has nutrition inline."""
)

grocery_agent = LlmAgent(
    name="grocery_agent",
    model=MODEL,
    output_key="grocery_list",
    instruction="""You are a grocery planner.
    Meal plan is in session state as 'meal_plan'.
    User profile is in session state as 'user_profile'.
    Consolidate ALL ingredients for the full week for num_people people.
    Combine duplicates, sum quantities.

    Format EXACTLY like this — no boxes, no lines, clean text only:

    VEGETABLES
      Onion           2 kg       ₹80
      Tomato          2 kg       ₹60
      [continue all items]
      Subtotal  ₹XXX

    DAIRY
      [items]
      Subtotal  ₹XXX

    GRAINS & CEREALS
      [items]
      Subtotal  ₹XXX

    PULSES & LEGUMES
      [items]
      Subtotal  ₹XXX

    SPICES & CONDIMENTS
      [items]
      Subtotal  ₹XXX

    OTHER
      [items]
      Subtotal  ₹XXX

    TOTAL ESTIMATED COST  ₹XXXX

    Output only the grocery list. No intro, no commentary."""
)

storefinder_agent = LlmAgent(
    name="storefinder_agent",
    model=MODEL,
    output_key="store_results",
    tools=[maps_tools],
    instruction="""You are the final presenter for NutriPlan.
    Read from session state:
    - 'user_profile' for location
    - 'meal_plan' for the full 7-day plan
    - 'grocery_list' for shopping items

    Use search_places to find 3 nearby supermarkets.
    Use calculate_distance_matrix for travel times.
    If maps tools fail or return no results, use your knowledge of
    well-known stores in that area and mark distances as approximate.

    Output the COMPLETE final response in clean plain text — NO boxes,
    NO horizontal lines, NO special border characters.
    Just emojis, headings, and content. Like this:


    🥗 NUTRIPLAN — YOUR WEEKLY PLAN


    📅 7-DAY MEAL PLAN WITH NUTRITION

    [Copy the COMPLETE meal plan from session state 'meal_plan' here
     exactly as formatted — all 7 days, per-meal nutrition with a hyphen
     after Breakfast / Lunch / Dinner, day totals, and weekly summary]


    🛒 GROCERY LIST

    [Copy the COMPLETE grocery list from session state 'grocery_list'
     here exactly as formatted — all categories, subtotals, grand total]


    🏪 NEAREST STORES

    1.  [Store Name]
        [Address]
        [X km away]   [X mins drive]

    2.  [Store Name]
        [Address]
        [X km away]   [X mins drive]

    3.  [Store Name]
        [Address]
        [X km away]   [X mins drive]


    📧 Want me to email this plan to you? Just share your email address!"""
)

email_agent = LlmAgent(
    name="email_agent",
    model=MODEL,
    tools=[email_tool],
    instruction="""You are an email sending assistant.
    Read 'meal_plan', 'grocery_list', and 'store_results' from session state.

    Compile into one clean text string:
    - Full 7-day meal plan with nutrition from meal_plan
    - Full grocery list from grocery_list
    - Store list from store_results

    Use send_plan_email with:
    - recipient_email: email address the user provided
    - plan_content: the complete compiled text above

    After tool responds confirm:
    "✅ Plan sent to [email]!
    Check your inbox — it includes your full meal plan, nutrition info,
    grocery list and nearby stores. Happy cooking! 🥗" """
)

# --- Planning Pipeline ---

planning_pipeline = SequentialAgent(
    name="planning_pipeline",
    sub_agents=[
        profile_agent,
        meal_planner_agent,
        recipe_nutrition_agent,
        grocery_agent,
        storefinder_agent,
    ]
)

# --- Root Agent ---

root_agent = LlmAgent(
    name="nutri_plan",
    model=MODEL,
    instruction="""You are NutriPlan 🥗, a friendly AI meal planning assistant.

    When a user provides dietary needs, budget and/or location:
    → Immediately transfer to planning_pipeline. No questions first.
    → After planning_pipeline finishes, stay completely silent.
      Do NOT summarise or add anything. Wait for user's next message.

    If the user provides an email address:
    → Transfer to email_agent.

    If the user says hi or asks what you do:
    → Reply:
    "Hi! I am NutriPlan 🥗

    Tell me your dietary needs, weekly budget and location and I will:

    📅  Plan your 7-day meals with per-meal nutrition breakdown
    🛒  Build your complete grocery list with INR costs
    🏪  Find the nearest stores to you
    📧  Email the complete plan to your inbox

    Just tell me your preferences to get started!" """,
    sub_agents=[planning_pipeline, email_agent]
)